# Generated by Django 5.0.14 on 2026-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
