# Generated by Django and Antigravity

from django.db import migrations, models
import django.db.models.deletion


def migrate_images(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductImage = apps.get_model("products", "ProductImage")

    for product in Product.objects.all():
        if product.image:
            ProductImage.objects.create(
                product=product, image=product.image, is_primary=True, ordering=0
            )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/images/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.Product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.RunPython(migrate_images, reverse_code=migrations.RunPython.noop),
    ]
