# Generated by Django and Antigravity

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_image_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
