# Generated by Django 5.0.14 on 2026-02-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
